package com.example.drawingandtexteditingapp

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material3.Slider
import androidx.compose.material3.SliderDefaults
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

@Composable
fun TonerSlider(
    currentHue: Float,
    currentSaturation: Float,
    currentValue: Float, // 0.0 to 1.0
    onValueChanged: (Float) -> Unit
) {
    // The pure color generated by the wheel, assuming full brightness (Value = 1f)
    val baseColor = Color.hsv(currentHue, currentSaturation, 1f)

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(40.dp)
            .background(
                brush = Brush.horizontalGradient(
                    colors = listOf(Color.Black, baseColor) // Gradient from Black to pure color
                )
            )
    ) {
        Slider(
            value = currentValue,
            onValueChange = onValueChanged,
            valueRange = 0f..1f,
            colors = SliderDefaults.colors(
                thumbColor = Color.White, // Makes the slider thumb visible over the gradient
                activeTrackColor = Color.Transparent,
                inactiveTrackColor = Color.Transparent
            )
        )
    }
}